# Copyright (c) 2026, Devich Daniel and Contributors
# See license.txt
"""GENERATED — do not edit by hand.

Regenerate with ``python3 scripts/generate_post_event_codes.py`` after
refreshing ``tests/fixtures/austrian_post_event_reason_list.xlsx`` from
secure.post.at/downloads/EventReasonList.xlsx. The generator carries the
classification rules and the reasoning behind them.
"""

from .status_mapping import (
    STATUS_DELIVERED,
    STATUS_OUT_FOR_DELIVERY,
    STATUS_PROBLEM,
    STATUS_READY_FOR_PICKUP,
    STATUS_RETURNED,
)

#: (ParcelEventTypeCode, ParcelEventReasonCode) -> the Post's own German
#: wording. Used as the event description, so a row reads as a sentence
#: rather than as two three-letter codes.
EVENT_TEXTS: dict[tuple[str, str], str] = {  # 366 pairs
    ("ANA", "AAO"): 'Sendung zum Transport erhalten',
    ("ANA", "AAQ"): 'Sendung zum Transport erhalten',
    ("ANA", "AO"): 'Sendung zum Transport erhalten',
    ("ANA", "AP"): 'Sendungsannahme an AllesPost-Adresse',
    ("ANA", "AQS"): 'Sendung zum Transport erhalten',
    ("ANA", "LA"): 'Sendung zum Transport erhalten',
    ("ANA", "PT"): 'Sendung zum Transport erhalten',
    ("ANA", "RA"): 'Sendung zum Transport erhalten',
    ("ANA", "VB"): 'Sendung zum Transport erhalten',
    ("ANI", "AI"): 'Sendung zum Transport erhalten',
    ("AVI", "AVS"): 'Elektronische Auftragsdaten wurden vom Versender storniert',
    ("AVI", "SE"): 'Elektronische Auftragsdaten wurden vom Versender übermittelt',
    ("AZT", "AT"): 'Sendung in Zustellung',
    ("BAU", "DD"): 'Sendung in Verteilung',
    ("BAU", "DS"): 'Sendung in Verteilung',
    ("BAU", "DZ"): 'Sendung in Verteilung',
    ("BAU", "HSU"): 'Sendung zum Transport erhalten',
    ("BEI", "EAW"): 'Sendung abholbereit',
    ("BEI", "EI"): 'Sendung in Post-Geschäftsstelle eingelangt',
    ("BEI", "EZ"): 'Sendung in Verteilung',
    ("BEI", "NBU"): 'Sendung in Verteilung',
    ("BEI", "VE"): 'Sendung in Verteilung',
    ("BEI", "XX"): 'Sendung in Verteilung',
    ("BEI", "ZTE"): 'Zum Transport erhalten',
    ("BNT", "1012"): 'Postaufgabe',
    ("BNT", "1070"): 'Sendung avisiert',
    ("BNT", "1071"): 'Sendung verlässt Österreich',
    ("BNT", "1072"): 'Sendung im Zielland angekommen',
    ("BNT", "1073"): 'Sendung zum Auslandstransport übergeben',
    ("BNT", "1074"): 'Sendung am internationalen Transport',
    ("BNT", "1075"): 'Sendung vom Frächter zum Transport erhalten',
    ("BNT", "1076"): 'Rückgabe der Sendung an den Absender',
    ("BNT", "1077"): 'Sendung für definierten Service angenommen',
    ("BNT", "1078"): 'Sendung vom Frächter in Beladungsplan zugewiesen',
    ("BNT", "1079"): 'Sendung vom Frächter nicht verladen',
    ("BNT", "1080"): 'Ankunft der Sendung am Dock oder Gate',
    ("BNT", "1081"): 'Sendung in Ziel-Transporteinrichtung angekommen',
    ("BNT", "1082"): 'Sendung vom Frächter an Frächter übergeben',
    ("BNT", "1083"): 'Sendung vom Frächter angenommen',
    ("BNT", "1084"): 'Sendung im Zielland angekommen',
    ("BNT", "1090"): 'Sendung auf dem Weg zur Post',
    ("BNT", "1323"): 'retour/rückgesendet',
    ("BNT", "1327"): 'retour/rückgesendet',
    ("BNT", "1566"): 'Sendung an Zoll übergeben',
    ("BNT", "1567"): 'Sendung in Bearbeitung Österreich',
    ("BNT", "1601"): 'Verzögerung bei Zollstellung wegen mangelhafter Zollerklärung',
    ("BNT", "1602"): 'Verzögerung wegen fehlender Zollpapiere/Rechnung',
    ("BNT", "1603"): 'Verzögerung bei Zollstellung wegen fehlender Importlizenz',
    ("BNT", "1604"): 'Verzögerung bei Zollstellung wegen fehlendem Ursprungszertifikat',
    ("BNT", "1605"): 'Sonstiges Zollstellungshindernis',
    ("BNT", "1606"): 'Sendung unvollständig',
    ("BNT", "1607"): 'Verzögerung bei Zollstellung wegen fehlendem Rücksendezertifikat',
    ("BNT", "1609"): 'Verzögerung wegen verbotenem Inhalt',
    ("BNT", "1610"): 'Sendung im Zollstellungsprozess',
    ("BNT", "1611"): 'Sendung zollfrei abgefertigt',
    ("BNT", "1612"): 'Sendung verzollt',
    ("BNT", "1613"): 'Sendung ins Ausland weitergeleitet',
    ("BNT", "1616"): 'Lagerausgang zur Verzollung/Bearbeitung',
    ("BNT", "1618"): 'Retour - Zollabfertigung nicht möglich',
    ("BNT", "1621"): 'Annahme verweigert',
    ("BNT", "1622"): 'Empfänger unbekannt/verzogen',
    ("BNT", "1623"): 'Empfängeradresse ungenügend',
    ("BNT", "1624"): 'Keine Rückmeldung vom Empfänger',
    ("BNT", "2007"): 'Sendung abholbereit',
    ("BNT", "2008"): 'Zugestellt',
    ("BNT", "2009"): 'Zugestellt',
    ("BNT", "2010"): 'Zugestellt',
    ("BNT", "2011"): 'Zugestellt',
    ("BNT", "2012"): 'retour - Zustellhindernis',
    ("BNT", "2013"): 'retour - Zustellhindernis',
    ("BNT", "2014"): 'retour - Zustellhindernis',
    ("BNT", "2015"): 'retour - nicht behoben',
    ("BNT", "2017"): 'an Ersatzempfänger übergeben',
    ("BNT", "2018"): 'retour/rückgesendet',
    ("BNT", "2022"): 'Zugestellt',
    ("BNT", "2024"): 'Zugestellt',
    ("BNT", "2028"): 'retour - nicht behoben',
    ("BNT", "2029"): 'in der Filiale ausgefolgt',
    ("BNT", "2034"): 'in Post-Empfangsbox eingelegt',
    ("BNT", "2036"): 'aus Post-Empfangsbox entnommen',
    ("BNT", "2039"): 'Sendung abholbereit',
    ("BNT", "2040"): 'retour - Zustellhindernis',
    ("BNT", "2042"): 'in Zustellung',
    ("BNT", "2043"): 'Postaufgabe',
    ("BNT", "2045"): 'Sendung in Bearbeitung Aufgabeland',
    ("BNT", "2046"): 'Sendung von Postbetreiber Zielland übernommen',
    ("BNT", "2047"): 'Sendung an Zoll übergeben',
    ("BNT", "2051"): 'Sendung in Bearbeitung Zielland',
    ("BNT", "2052"): 'im Zustellprozess',
    ("BNT", "2053"): 'Sendung in Zustellung',
    ("BNT", "2054"): 'Sendung in Zustellung Österreich',
    ("BNT", "2055"): 'erfolgloser Zustellversuch',
    ("BNT", "2056"): 'eingeworfen',
    ("BNT", "2057"): 'Sendung für Auslandstransport bereit',
    ("BNT", "2058"): 'Sendung in Österreich angekommen',
    ("BNT", "2059"): 'Zugestellt',
    ("BNT", "2060"): 'Transit',
    ("BNT", "2061"): 'Transit',
    ("BNT", "2062"): 'Postaufgabe im Ausland',
    ("BNT", "2063"): 'Sendung in Bearbeitung Aufgabeland',
    ("BNT", "2064"): 'Sendung für Auslandstransport bereit',
    ("BNT", "2065"): 'erfolgloser Zustellversuch',
    ("BNT", "2066"): 'Zugestellt',
    ("BNT", "2067"): 'Transit',
    ("BNT", "2068"): 'Transit',
    ("BNT", "2069"): 'in Post-Abholwand eingelegt',
    ("BNT", "2070"): 'aus Post-Abholwand entnommen',
    ("BNT", "2071"): 'aus Post-Abholwand entnommen',
    ("BNT", "2074"): 'Postaufgabe',
    ("BNT", "2075"): 'Sendung avisiert',
    ("BNT", "2076"): 'Postaufgabe',
    ("BNT", "2085"): 'erfolgloser Zustellversuch – Empfänger benachrichtigt',
    ("BNT", "2086"): 'erfolgloser Zustellversuch – Sendung retour',
    ("BNT", "2402"): 'retour - Zustellhindernis',
    ("BNT", "2403"): 'retour - Zustellhindernis',
    ("BNT", "2404"): 'retour - Zustellhindernis',
    ("BNT", "2409"): 'retour - Zustellhindernis',
    ("BNT", "2416"): 'retour - Zustellhindernis',
    ("BNT", "5001030"): 'im Zustellprozess',
    ("BNT", "5001031"): 'benachrichtigt',
    ("BNT", "5001035"): 'benachrichtigt',
    ("BNT", "5001036"): 'benachrichtigt',
    ("BNT", "5001037"): 'benachrichtigt',
    ("BNT", "5001051"): 'retour/rückgesendet',
    ("BNT", "5001052"): 'retour/rückgesendet',
    ("BNT", "5001053"): 'verweigert',
    ("BNT", "5001054"): 'retour/rückgesendet',
    ("BNT", "5001300"): 'benachrichtigt',
    ("BNT", "5001301"): 'kassiert',
    ("BNT", "5001302"): 'kassiert',
    ("BNT", "5001303"): 'kassiert',
    ("BNT", "5001304"): 'kassiert',
    ("BNT", "5001305"): 'im Zustellprozess',
    ("BNT", "5001306"): 'im Zustellprozess',
    ("BNT", "5001307"): 'retour/rückgesendet',
    ("BNT", "5001308"): 'retour/rückgesendet',
    ("BNT", "5001309"): 'retour/rückgesendet',
    ("BNT", "5001310"): 'retour/rückgesendet',
    ("BNT", "5001311"): 'retour/rückgesendet',
    ("BNT", "5001317"): 'hinterlegt',
    ("BNT", "5001318"): 'kassiert',
    ("BNT", "5001321"): 'retour/rückgesendet',
    ("BNT", "5001401"): 'kassiert',
    ("BNT", "5001910"): 'retour/rückgesendet',
    ("BNT", "5001920"): 'kassiert',
    ("BNT", "5001926"): 'kassiert',
    ("BNT", "5001930"): 'retour/rückgesendet',
    ("BNT", "5001980"): 'retour/rückgesendet',
    ("BNT", "5002354"): 'kassiert',
    ("BNT", "5002355"): 'angewiesen',
    ("CLA", "CAC"): 'Sendung in Klärung',
    ("CLA", "CAF"): 'Zur Klärung an Post-Geschäftsstelle',
    ("CLA", "CAH"): 'Sendung in Klärung',
    ("CLA", "CAM"): 'Sendung in Klärung',
    ("CLA", "CAN"): 'Sendung in Klärung',
    ("CLA", "CAV"): 'Sendung in Klärung',
    ("CLA", "CAW"): 'Sendung in Klärung',
    ("CLA", "CAX"): 'Sendung in Klärung',
    ("CLA", "CEU"): 'Sendung in Klärung',
    ("CLA", "CEV"): 'Sendung in Klärung',
    ("CLA", "CFA"): 'Sendung in Klärung',
    ("CLA", "CFU"): 'Sendung in Klärung',
    ("CLA", "CGG"): 'Sendung in Klärung',
    ("CLA", "CIF"): 'Sendung in Klärung',
    ("CLA", "CNK"): 'Sendung in Klärung',
    ("CLA", "CNN"): 'Sendung in Klärung',
    ("CLA", "CNR"): 'Sendung in Klärung',
    ("CLA", "CNU"): 'Sendung in Klärung',
    ("CLA", "COS"): 'Sendung in Klärung',
    ("CLA", "CSH"): 'Sendung in Klärung',
    ("CLA", "CST"): 'Sendung in Klärung',
    ("CLA", "CTG"): 'Sendung in Klärung',
    ("CLA", "ZVE"): 'Sendung in Klärung',
    ("CUD", "CE"): 'Verzögerung der Zollanmeldung - fehlende/magelhafte Zollerklärung',
    ("CUD", "CFD"): 'Dem Zoll zur Selbstverzollung übergeben',
    ("CUD", "CG"): 'Verzögerung bei Zollstellung wegen mangelnder Einfuhrinformation',
    ("CUD", "CH"): 'Verzögerung bei Zollstellung wegen fehlender Zolldokumente',
    ("CUD", "CI"): 'Verzögerung der Zollanmeldung - fehlender Wertnachweis',
    ("CUD", "CJ"): 'Verzögerung wegen verbotenem Inhalt',
    ("CUD", "CK"): 'Verzögerung bei Zollstellung wegen mangelhafter Rechnung',
    ("CUD", "CL"): 'Verzögerung der Zollanmeldung - fehlende Importlizenz',
    ("CUD", "CLA"): 'Verzögerung der Zollanmeldung - fehlende Einfuhrbewilligung Außenhandelsgesetz',
    ("CUD", "CLAM"): 'Verzögerung der Zollanmeldung - fehlende Einfuhrgenehmigung',
    ("CUD", "CLAS"): 'Verzögerung der Zollanmeldung - fehlende Einfuhrgenehmigung',
    ("CUD", "CLPD"): 'Verzögerung der Zollanmeldung - fehlende Bestätigung betreffend Einfuhrprivilegien',
    ("CUD", "CLTA"): 'Verzögerung der Zollanmeldung - fehlende Einfuhrgenehmigung',
    ("CUD", "CLW"): 'Verzögerung der Zollanmeldung - fehlende Einfuhrgenehmigung',
    ("CUD", "CM"): 'Verzögerung bei Zollstellung wegen Einfuhrverbot im Bestimmungsland',
    ("CUD", "CN"): 'Verzögerung bei Zollstellung wegen fehlender UID/Importnummer',
    ("CUD", "CO"): 'Verzögerung bei Zollstellung wegen fehlendem Ursprungszertifikat',
    ("CUD", "COT"): 'Verzögerung der Zollanmeldung',
    ("CUD", "CP"): 'Verzögerung bei Zollstellung wegen mangelhaftem Urspungszertifikat',
    ("CUD", "CQ"): 'Sendung vom Zoll ohne Angabe von Gründen zurückgehalten',
    ("CUD", "CS"): 'Einfuhrverbot-Absender verständigt',
    ("CUD", "CSI"): 'Verzögerung der Zollanmeldung - Sendung unvollständig',
    ("CUD", "CU"): 'Verzögerung der Zollanmeldung - fehlendes Rücksendezertifikat',
    ("CUD", "CVNP"): 'Verzögerung der Zollanmeldung - unplausibler Warenwert',
    ("CUD", "CZ"): 'Verzögerung bei Zollstellung wegen fehlender Zollerklärung',
    ("CUD", "IP"): 'Einfuhrverbot im Bestimmungsland',
    ("CUS", "CA"): 'Sendung im Zollanmeldungsprozess',
    ("CUS", "CF"): 'Sendung im Zollstellungsprozess',
    ("CUS", "CR"): 'Zollanmeldung abgeschlossen',
    ("CUS", "EX400M"): 'Ausfuhranmeldung übermittelt',
    ("CUS", "EXA"): 'Sendung bei Zoll-/ Sicherheitskontrolle',
    ("CUS", "EXC"): 'Sendung im Zollstellungsprozess',
    ("DAM", "BF"): 'Verzögerung - Schadensprotokoll erstellt',
    ("DAM", "BFM"): 'Verzögerung - Schadensprotokoll erstellt',
    ("DAM", "BS"): 'Verzögerung wegen Beschädigung - Inhaltsprüfung',
    ("DAM", "MAV"): 'Mangelhafte Verpackung ausgebessert',
    ("DAM", "NV"): 'Verzögerung - Verpackung ausgebessert',
    ("DIC", "BU"): 'Sendung in Verteilung',
    ("DIC", "IV"): 'Sendung in Verteilung',
    ("DKT", "DO"): 'Sendung abholbereit',
    ("EXP", "AMU"): 'Sendung am Flughafen übergeben',
    ("EXP", "EXD"): 'Verzögerung – Sendung in Klärung',
    ("EXP", "R23"): 'Sendung am Zielflughafen angekommen',
    ("EXP", "XA"): 'Sendung ins Zielland weitergeleitet',
    ("HIA", "HD"): 'Sendung im Depot abholbereit',
    ("HIA", "HO"): 'Sendung abholbereit',
    ("IMP", "EDA"): 'Verzögerung – Sendung in Klärung',
    ("IMP", "IB"): 'Sendung im Bestimmungsland eingetroffen',
    ("IMP", "IM"): 'Sendung in Österreich eingetroffen',
    ("KAM", "AB"): 'Unvorhergesehenes Zustellhindernis',
    ("KAM", "ET"): 'Unvorhergesehenes Zustellhindernis',
    ("KAM", "SN"): 'Unvorhergesehenes Zustellhindernis',
    ("LAA", "AL"): 'Lagerausgang zur Zollanmeldung/Bearbeitung',
    ("LAG", "ALZ"): 'Lagerausgang zur Zollanmeldung/Bearbeitung',
    ("LAG", "EL"): 'Lagereingang - Zollanmeldungshindernis',
    ("LAG", "ELE"): 'Lagereingang - Zollanmeldungshindernis',
    ("LAG", "LE"): 'Sendung im Postlager eingelangt',
    ("LAG", "WZ"): 'Sendung in Verteilung',
    ("NNI", "BW"): 'Nachnahmebetrag intern abgerechnet',
    ("NNI", "BX"): 'Nachnahmebetrag zur Überweisung verarbeitet',
    ("ONT", "ON"): 'Sendung in Zustellung',
    ("ONT", "OT"): 'Sendung in Zustellung',
    ("PKI", "EBE"): 'Sendung benachrichtigt',
    ("PKI", "FX"): 'Elektronische Ankündigung fehlerhaft (Adressfehler)',
    ("PKI", "PB"): 'e-Benachrichtigung versendet (Erinnerung)',
    ("PKI", "PD"): 'Zweite Benachrichtigung zugestellt',
    ("PKI", "WD"): 'Elektronische Ankündigung fehlerhaft',
    ("PUG", "RT"): 'Übergabe an Kooperationspartner',
    ("PUG", "UB"): 'Übergabe an Zustellpartner',
    ("PUG", "UH"): 'Sendung in Post-Geschäftsstelle (Postfach)',
    ("PUG", "UL"): 'Sendung in Post-Geschäftsstelle eingelangt',
    ("PUG", "UPB"): 'Sendung abholbereit',
    ("PUG", "UR"): 'Übergabe an Kooperationspartner',
    ("PUG", "US"): 'Übergabe an Zustellpartner',
    ("PUG", "UT"): 'Übergabe an Kooperationspartner',
    ("PUG", "ZO"): 'Sendung in Zustellung',
    ("PUH", "AG"): 'Abholauftrag storniert',
    ("PUH", "KA"): 'Abholhindernis',
    ("PUH", "KN"): 'Abholhindernis',
    ("PUH", "KS"): 'Abholhindernis',
    ("PUH", "KW"): 'Abholhindernis',
    ("PUH", "PF"): 'Abholhindernis',
    ("PUP", "AA"): 'Abholauftrag eingegangen',
    ("PUP", "AE"): 'Sendung zum Transport erhalten',
    ("RTS", "AQ"): 'Retour - Annahme verweigert',
    ("RTS", "AR"): 'Rücksendung',
    ("RTS", "AU"): 'Rücksendung',
    ("RTS", "CX"): 'Rücksendung',
    ("RTS", "ER"): 'Rücksendung',
    ("RTS", "HR"): 'Rücksendung',
    ("RTS", "IR"): 'Rücksendung',
    ("RTS", "NBS"): 'Rücksendung',
    ("RTS", "RE"): 'Rücksendung',
    ("RTS", "RED"): 'Rücksendung',
    ("RTS", "RN"): 'Rücksendung',
    ("RTS", "RP"): 'Rücksendung',
    ("RTS", "RS"): 'Rücksendung',
    ("RTS", "RU"): 'Rücksendung',
    ("RTS", "RV"): 'Rücksendung',
    ("RTS", "SB"): 'Rücksendung',
    ("SIN", "EX400A"): 'Ausfuhranmeldung übermittelt',
    ("SIN", "EX431"): 'Austrittsbescheinigung',
    ("SIN", "EZ900ED"): 'Ausfuhranmeldung - Dokumentenanforderung',
    ("SIN", "EZ902ED"): 'Ausfuhranmeldung - Keine Freigabe',
    ("SIN", "EZ903ED"): 'Ausfuhranmeldung - Kontrollankündigung',
    ("SIN", "EZ923ED"): 'Ausfuhranmeldung - Freigabe',
    ("SIN", "FFC"): 'Zollanmeldungshindernis - Rückmeldung vom Empfänger eingelangt',
    ("SIN", "FFCNA"): 'Zollanmeldungshindernis - Rückmeldung vom Empfänger mit Annahmeverweigerung',
    ("SIN", "IMI"): 'Elektronische Auftragsdaten wurden vom Versender übermittelt',
    ("SIN", "KAN"): 'Keine Annahme aufgrund Beschädigung',
    ("SIN", "SIU"): 'Sendung ist unterwegs',
    ("SIN", "UFR"): 'Unterfrankierung Paketmarke',
    ("TRA", "TA"): 'Transit',
    ("TRA", "TD"): 'Transitsendung – Beschädigung festgestellt',
    ("TRA", "TE"): 'Transit',
    ("TRA", "TR"): 'Transit',
    ("TRA", "TRC"): 'Konsolidierung für Export',
    ("TRA", "TRD"): 'Auflösung einer konsolidierten Sendung',
    ("VEH", "GF"): 'Verzögerung durch mangelhafte Angaben/Papiere',
    ("VEH", "NS"): 'Verzögerung - nicht systemkonform',
    ("VER", "SW"): 'Sendung in Verteilung',
    ("VER", "VT"): 'Sendung in Verteilung',
    ("VER", "WC"): 'Sendung in Verteilung',
    ("WLT", "PL"): 'Sendung an das Postlager weitergeleitet',
    ("WLT", "UML"): 'Sendung wurde umgeleitet',
    ("WLT", "WL"): 'Sendung wurde weitergeleitet',
    ("ZSS", "FB"): 'Rücknahme nach Ausfolgung',
    ("ZUH", "AC"): 'Annahme verweigert - Lieferung zu spät',
    ("ZUH", "AH"): 'Annahme verweigert - beschädigt',
    ("ZUH", "AM"): 'Annahme verweigert - Teillieferung',
    ("ZUH", "AN"): 'Annahme verweigert - Nachnahme falsch',
    ("ZUH", "AV"): 'Annahme verweigert',
    ("ZUH", "AW"): 'Annahme verweigert - Ansprechpartner fehlt',
    ("ZUH", "AX"): 'Annahme verweigert - nicht bestellt',
    ("ZUH", "BC"): 'Anschriftsproblem',
    ("ZUH", "BH"): 'Sendung in Zustellung',
    ("ZUH", "BN"): 'Sendung in Zustellung',
    ("ZUH", "EU"): 'Empfänger unbekannt/verzogen',
    ("ZUH", "EV"): 'Sendung konnte nicht zugestellt werden',
    ("ZUH", "FA"): 'Empfängeradresse ungenügend',
    ("ZUH", "FG"): 'Firma (vorübergehend) geschlossen',
    ("ZUH", "FL"): 'Verzögerung wegen Fehlverteilung',
    ("ZUH", "FLP"): 'Verzögerung wegen Fehlleitung von unserem Partner',
    ("ZUH", "FT"): 'Verzögerung wegen lokalem Feiertag',
    ("ZUH", "FU"): 'Empfänger im Urlaub',
    ("ZUH", "GG"): 'Verzögerung durch mangelhafte Angaben/Papiere',
    ("ZUH", "HB"): 'Sendung in Zustellung',
    ("ZUH", "HG"): 'Verzögerung - unvorhersehbares Zustellhindernis',
    ("ZUH", "HS"): 'Sendung abholbereit',
    ("ZUH", "IF"): 'Verzögerung durch mangelhafte Angaben/Papiere',
    ("ZUH", "KG"): 'Verzögerung wegen Zustellhindernis',
    ("ZUH", "NB"): 'Sendung noch nicht abgeholt',
    ("ZUH", "ND"): 'Sendung in Zustellung',
    ("ZUH", "NG"): 'Sendung in Zustellung',
    ("ZUH", "NH"): 'Sendung in Zustellung',
    ("ZUH", "NN"): 'Nachnahmebetrag unklar',
    ("ZUH", "NR"): 'Verzögerung durch fehlende Nachnahmedaten',
    ("ZUH", "NZ"): 'Sendung wird nochmals zugestellt',
    ("ZUH", "OB"): 'Sendung noch nicht abgeholt',
    ("ZUH", "OC"): 'Sendung in Zustellung',
    ("ZUH", "OH"): 'Sendung abholbereit',
    ("ZUH", "OS"): 'Verzögerung - unvorhersehbares Zustellhindernis',
    ("ZUH", "OV"): 'Verzögerung - unvorhersehbares Zustellhindernis',
    ("ZUH", "OW"): 'Verzögerung - unvorhersehbares Zustellhindernis',
    ("ZUH", "OX"): 'Verzögerung - unvorhersehbares Zustellhindernis',
    ("ZUH", "SF"): 'Sendung in Zustellung',
    ("ZUH", "SH"): 'Verzögerung wegen Zustellhindernis',
    ("ZUH", "TG"): 'Verzögerung wegen Zustellhindernis',
    ("ZUH", "TV"): 'Sendung in Zustellung',
    ("ZUH", "XAV"): 'Annahme verweigert',
    ("ZUH", "XEU"): 'Empfänger unbekannt/verzogen',
    ("ZUH", "XFA"): 'Empfängeradresse ungenügend',
    ("ZUH", "XNB"): 'Keine Rückmeldung vom Empfänger',
    ("ZUS", "BK"): 'Sendung im Postkasten zugestellt',
    ("ZUS", "HH"): 'Sendung wurde zugestellt',
    ("ZUS", "SA"): 'Sendung wurde zugestellt',
    ("ZUS", "SV"): 'Sendung wurde zugestellt',
    ("ZUS", "SZD"): 'Sendung zugestellt (Digitalisierung)',
    ("ZUS", "VU"): 'Sendung wurde zugestellt',
    ("ZUS", "ZA"): 'Sendung zugestellt',
    ("ZUS", "ZAW"): 'Sendung wurde zugestellt',
    ("ZUS", "ZB"): 'Sendung wurde zugestellt',
    ("ZUS", "ZE"): 'Sendung wurde zugestellt',
    ("ZUS", "ZK"): 'Sendung wurde zugestellt',
    ("ZUS", "ZM"): 'Sendung wurde zugestellt',
    ("ZUS", "ZN"): 'Sendung wurde zugestellt',
    ("ZUS", "ZP"): 'Sendung wurde zugestellt',
    ("ZUS", "ZPB"): 'Sendung wurde zugestellt',
    ("ZUS", "ZS"): 'Sendung wurde zugestellt',
    ("ZUS", "ZU"): 'Sendung wurde zugestellt',
    ("ZUS", "ZV"): 'Sendung wurde zugestellt',
    ("ZUS", "ZW"): 'Sendung wurde zugestellt',
    ("ZUS", "ZY"): 'Sendung wurde zugestellt',
}

#: The pairs whose official wording names the event outcome — delivered,
#: ready for pickup, out for delivery, returned, problem. For these the
#: event row shows its own meaning; ShipmentState (the parcel's state at
#: FILE-CREATION time) stays the fallback for everything unclassified.
EVENT_OVERRIDES: dict[tuple[str, str], str] = {  # 151 pairs
    ("AZT", "AT"): STATUS_OUT_FOR_DELIVERY,
    ("BEI", "EAW"): STATUS_READY_FOR_PICKUP,
    ("BNT", "1076"): STATUS_RETURNED,
    ("BNT", "1079"): STATUS_PROBLEM,
    ("BNT", "1323"): STATUS_RETURNED,
    ("BNT", "1327"): STATUS_RETURNED,
    ("BNT", "1605"): STATUS_PROBLEM,
    ("BNT", "1609"): STATUS_PROBLEM,
    ("BNT", "1618"): STATUS_RETURNED,
    ("BNT", "1621"): STATUS_PROBLEM,
    ("BNT", "1622"): STATUS_PROBLEM,
    ("BNT", "1623"): STATUS_PROBLEM,
    ("BNT", "2007"): STATUS_READY_FOR_PICKUP,
    ("BNT", "2008"): STATUS_DELIVERED,
    ("BNT", "2009"): STATUS_DELIVERED,
    ("BNT", "2010"): STATUS_DELIVERED,
    ("BNT", "2011"): STATUS_DELIVERED,
    ("BNT", "2012"): STATUS_RETURNED,
    ("BNT", "2013"): STATUS_RETURNED,
    ("BNT", "2014"): STATUS_RETURNED,
    ("BNT", "2015"): STATUS_RETURNED,
    ("BNT", "2017"): STATUS_DELIVERED,
    ("BNT", "2018"): STATUS_RETURNED,
    ("BNT", "2022"): STATUS_DELIVERED,
    ("BNT", "2024"): STATUS_DELIVERED,
    ("BNT", "2028"): STATUS_RETURNED,
    ("BNT", "2029"): STATUS_DELIVERED,
    ("BNT", "2034"): STATUS_READY_FOR_PICKUP,
    ("BNT", "2036"): STATUS_DELIVERED,
    ("BNT", "2039"): STATUS_READY_FOR_PICKUP,
    ("BNT", "2040"): STATUS_RETURNED,
    ("BNT", "2042"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "2052"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "2053"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "2054"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "2055"): STATUS_PROBLEM,
    ("BNT", "2056"): STATUS_DELIVERED,
    ("BNT", "2059"): STATUS_DELIVERED,
    ("BNT", "2065"): STATUS_PROBLEM,
    ("BNT", "2066"): STATUS_DELIVERED,
    ("BNT", "2069"): STATUS_READY_FOR_PICKUP,
    ("BNT", "2070"): STATUS_DELIVERED,
    ("BNT", "2071"): STATUS_DELIVERED,
    ("BNT", "2085"): STATUS_PROBLEM,
    ("BNT", "2086"): STATUS_RETURNED,
    ("BNT", "2402"): STATUS_RETURNED,
    ("BNT", "2403"): STATUS_RETURNED,
    ("BNT", "2404"): STATUS_RETURNED,
    ("BNT", "2409"): STATUS_RETURNED,
    ("BNT", "2416"): STATUS_RETURNED,
    ("BNT", "5001030"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "5001051"): STATUS_RETURNED,
    ("BNT", "5001052"): STATUS_RETURNED,
    ("BNT", "5001053"): STATUS_PROBLEM,
    ("BNT", "5001054"): STATUS_RETURNED,
    ("BNT", "5001305"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "5001306"): STATUS_OUT_FOR_DELIVERY,
    ("BNT", "5001307"): STATUS_RETURNED,
    ("BNT", "5001308"): STATUS_RETURNED,
    ("BNT", "5001309"): STATUS_RETURNED,
    ("BNT", "5001310"): STATUS_RETURNED,
    ("BNT", "5001311"): STATUS_RETURNED,
    ("BNT", "5001317"): STATUS_READY_FOR_PICKUP,
    ("BNT", "5001321"): STATUS_RETURNED,
    ("BNT", "5001910"): STATUS_RETURNED,
    ("BNT", "5001930"): STATUS_RETURNED,
    ("BNT", "5001980"): STATUS_RETURNED,
    ("CUD", "CJ"): STATUS_PROBLEM,
    ("CUD", "CM"): STATUS_PROBLEM,
    ("CUD", "CQ"): STATUS_PROBLEM,
    ("CUD", "CS"): STATUS_PROBLEM,
    ("CUD", "IP"): STATUS_PROBLEM,
    ("DAM", "BS"): STATUS_PROBLEM,
    ("DKT", "DO"): STATUS_READY_FOR_PICKUP,
    ("HIA", "HD"): STATUS_READY_FOR_PICKUP,
    ("HIA", "HO"): STATUS_READY_FOR_PICKUP,
    ("ONT", "ON"): STATUS_OUT_FOR_DELIVERY,
    ("ONT", "OT"): STATUS_OUT_FOR_DELIVERY,
    ("PUG", "UPB"): STATUS_READY_FOR_PICKUP,
    ("PUG", "ZO"): STATUS_OUT_FOR_DELIVERY,
    ("PUH", "KA"): STATUS_PROBLEM,
    ("PUH", "KN"): STATUS_PROBLEM,
    ("PUH", "KS"): STATUS_PROBLEM,
    ("PUH", "KW"): STATUS_PROBLEM,
    ("PUH", "PF"): STATUS_PROBLEM,
    ("RTS", "AQ"): STATUS_RETURNED,
    ("RTS", "AR"): STATUS_RETURNED,
    ("RTS", "AU"): STATUS_RETURNED,
    ("RTS", "CX"): STATUS_RETURNED,
    ("RTS", "ER"): STATUS_RETURNED,
    ("RTS", "HR"): STATUS_RETURNED,
    ("RTS", "IR"): STATUS_RETURNED,
    ("RTS", "NBS"): STATUS_RETURNED,
    ("RTS", "RE"): STATUS_RETURNED,
    ("RTS", "RED"): STATUS_RETURNED,
    ("RTS", "RN"): STATUS_RETURNED,
    ("RTS", "RP"): STATUS_RETURNED,
    ("RTS", "RS"): STATUS_RETURNED,
    ("RTS", "RU"): STATUS_RETURNED,
    ("RTS", "RV"): STATUS_RETURNED,
    ("RTS", "SB"): STATUS_RETURNED,
    ("SIN", "FFCNA"): STATUS_PROBLEM,
    ("SIN", "KAN"): STATUS_PROBLEM,
    ("SIN", "UFR"): STATUS_PROBLEM,
    ("TRA", "TD"): STATUS_PROBLEM,
    ("ZUH", "AC"): STATUS_PROBLEM,
    ("ZUH", "AH"): STATUS_PROBLEM,
    ("ZUH", "AM"): STATUS_PROBLEM,
    ("ZUH", "AN"): STATUS_PROBLEM,
    ("ZUH", "AV"): STATUS_PROBLEM,
    ("ZUH", "AW"): STATUS_PROBLEM,
    ("ZUH", "AX"): STATUS_PROBLEM,
    ("ZUH", "BC"): STATUS_PROBLEM,
    ("ZUH", "BH"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "BN"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "EU"): STATUS_PROBLEM,
    ("ZUH", "EV"): STATUS_PROBLEM,
    ("ZUH", "FA"): STATUS_PROBLEM,
    ("ZUH", "HB"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "HS"): STATUS_READY_FOR_PICKUP,
    ("ZUH", "ND"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "NG"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "NH"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "NZ"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "OC"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "OH"): STATUS_READY_FOR_PICKUP,
    ("ZUH", "SF"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "TV"): STATUS_OUT_FOR_DELIVERY,
    ("ZUH", "XAV"): STATUS_PROBLEM,
    ("ZUH", "XEU"): STATUS_PROBLEM,
    ("ZUH", "XFA"): STATUS_PROBLEM,
    ("ZUS", "BK"): STATUS_DELIVERED,
    ("ZUS", "HH"): STATUS_DELIVERED,
    ("ZUS", "SA"): STATUS_DELIVERED,
    ("ZUS", "SV"): STATUS_DELIVERED,
    ("ZUS", "SZD"): STATUS_DELIVERED,
    ("ZUS", "VU"): STATUS_DELIVERED,
    ("ZUS", "ZA"): STATUS_DELIVERED,
    ("ZUS", "ZAW"): STATUS_DELIVERED,
    ("ZUS", "ZB"): STATUS_DELIVERED,
    ("ZUS", "ZE"): STATUS_DELIVERED,
    ("ZUS", "ZK"): STATUS_DELIVERED,
    ("ZUS", "ZM"): STATUS_DELIVERED,
    ("ZUS", "ZN"): STATUS_DELIVERED,
    ("ZUS", "ZP"): STATUS_DELIVERED,
    ("ZUS", "ZPB"): STATUS_DELIVERED,
    ("ZUS", "ZS"): STATUS_DELIVERED,
    ("ZUS", "ZU"): STATUS_DELIVERED,
    ("ZUS", "ZV"): STATUS_DELIVERED,
    ("ZUS", "ZW"): STATUS_DELIVERED,
    ("ZUS", "ZY"): STATUS_DELIVERED,
}
